Public Class IOSEntityKeys
    Public Const TECHNOLOGY_2G As String = "2G"
    Public Const TECHNOLOGY_3G As String = "3G"
    Public Const TECHNOLOGY_4G As String = "4G"
End Class
Public Class IOSEntityKeys3G
    Public Const UARFCN As String = "UARFCN"
    Public Const CHANNELTYPE As String = "ChannelType"
    Public Const MSGRRC As String = "MsgRRC"
    Public Const NUMBEROFSC_AS As String = "NumberOfSC_AS"
    Public Const AS1_SC As String = "AS1_SC"
    Public Const AS1_RSCP As String = "AS1_RSCP"
    Public Const AS1_ECNO As String = "AS1_Ecno"
    Public Const AS2_SC As String = "AS2_SC"
    Public Const AS2_RSCP As String = "AS2_RSCP"
    Public Const AS2_ECNO As String = "AS2_Ecno"
    Public Const AS3_SC As String = "AS3_SC"
    Public Const AS3_RSCP As String = "AS3_RSCP"
    Public Const AS3_ECNO As String = "AS3_Ecno"
    Public Const AS1_CELLID As String = "AS1_CellId"
    Public Const AS2_CELLID As String = "AS2_CellId"
    Public Const AS3_CELLID As String = "AS3_CellId"
    Public Const NB1_SC As String = "NB1_SC"
    Public Const NB2_SC As String = "NB2_SC"
    Public Const NB3_SC As String = "NB3_SC"
    Public Const NB4_SC As String = "NB4_SC"
    Public Const NB5_SC As String = "NB5_SC"
    Public Const NB6_SC As String = "NB6_Sc"
    Public Const NB1_CELLID As String = "NB1_CellId"
    Public Const NB2_CELLID As String = "NB2_CellId"
    Public Const NB3_CELLID As String = "NB3_CellId"
    Public Const NB4_CELLID As String = "NB4_CellId"
    Public Const NB5_CELLID As String = "NB5_CellId"
    Public Const NB6_CELLID As String = "NB6_CellId"
    Public Const NB1_RSCP As String = "NB1_RSCP"
    Public Const NB2_RSCP As String = "NB2_RSCP"
    Public Const NB3_RSCP As String = "NB3_RSCP"
    Public Const NB4_RSCP As String = "NB4_RSCP"
    Public Const NB5_RSCP As String = "NB5_RSCP"
    Public Const NB6_RSCP As String = "NB6_RSCP"
    Public Const NB1_ECNO As String = "NB1_Ecno"
    Public Const NB2_ECNO As String = "NB2_Ecno"
    Public Const NB3_ECNO As String = "NB3_Ecno"
    Public Const NB4_ECNO As String = "NB4_Ecno"
    Public Const NB5_ECNO As String = "NB5_Ecno"
    Public Const NB6_ECNO As String = "NB6_Ecno"
    
End Class

Public Class IOSEntityKeys4G

    Public Const SC_CELLID As String = "SC_CELLID"
    Public Const SC_TAC As String = "SC_TAC"
    Public Const SC_PCI As String = "SC_PCI"
    Public Const SC_EARFCN As String = "SC_EARFCN"
    Public Const SC_RSRP As String = "SC_RSRP"
    Public Const SC_RSRQ As String = "SC_RSRQ"


    Public Const CHANNELTYPE As String = "ChannelType"
    Public Const MSGRRC As String = "MsgRRC"
    Public Const NUMBEROFPCI_S As String = "NumberOfPCI_S"
    Public Const N1_PCI As String = "N1_PCI"
    Public Const N2_PCI As String = "N2_PCI"
    Public Const N3_PCI As String = "N3_PCI"
    Public Const N4_PCI As String = "N4_PCI"
    Public Const N5_PCI As String = "N5_PCI"
    Public Const N6_PCI As String = "N6_PCI"
    Public Const N1_CELLID As String = "N1_CellId"
    Public Const N2_CELLID As String = "N2_CellId"
    Public Const N3_CELLID As String = "N3_CellId"
    Public Const N4_CELLID As String = "N4_CellId"
    Public Const N5_CELLID As String = "N5_CellId"
    Public Const N6_CELLID As String = "N6_CellId"
    Public Const N1_RSRP As String = "N1_RSRP"
    Public Const N2_RSRP As String = "N2_RSRP"
    Public Const N3_RSRP As String = "N3_RSRP"
    Public Const N4_RSRP As String = "N4_RSRP"
    Public Const N5_RSRP As String = "N5_RSRP"
    Public Const N6_RSRP As String = "N6_RSRP"
    Public Const N1_RSRQ As String = "N1_RSRQ"
    Public Const N2_RSRQ As String = "N2_RSRQ"
    Public Const N3_RSRQ As String = "N3_RSRQ"
    Public Const N4_RSRQ As String = "N4_RSRQ"
    Public Const N5_RSRQ As String = "N5_RSRQ"
    Public Const N6_RSRQ As String = "N6_RSRQ"

    Public Const D1_PCI As String = "D1_PCI"
    Public Const D2_PCI As String = "D2_PCI"
    Public Const D3_PCI As String = "D3_PCI"
    Public Const D4_PCI As String = "D4_PCI"
    Public Const D5_PCI As String = "D5_PCI"
    Public Const D6_PCI As String = "D6_PCI"
    Public Const D1_CELLID As String = "D1_CellId"
    Public Const D2_CELLID As String = "D2_CellId"
    Public Const D3_CELLID As String = "D3_CellId"
    Public Const D4_CELLID As String = "D4_CellId"
    Public Const D5_CELLID As String = "D5_CellId"
    Public Const D6_CELLID As String = "D6_CellId"
    Public Const D1_RSRP As String = "D1_RSRP"
    Public Const D2_RSRP As String = "D2_RSRP"
    Public Const D3_RSRP As String = "D3_RSRP"
    Public Const D4_RSRP As String = "D4_RSRP"
    Public Const D5_RSRP As String = "D5_RSRP"
    Public Const D6_RSRP As String = "D6_RSRP"
    Public Const D1_RSRQ As String = "D1_RSRQ"
    Public Const D2_RSRQ As String = "D2_RSRQ"
    Public Const D3_RSRQ As String = "D3_RSRQ"
    Public Const D4_RSRQ As String = "D4_RSRQ"
    Public Const D5_RSRQ As String = "D5_RSRQ"
    Public Const D6_RSRQ As String = "D6_RSRQ"

End Class
Public Class IOSEntityKeys2G
    Public Const CHANNELTYPE As String = "ChannelType"
    Public Const MSGL3 As String = "msgL3"

    Public Const RXLEVSUB As String = "RxLevSub"
    Public Const RXQUALSUB As String = "RxQualSub"
    Public Const SC_LAC As String = "SC_LAC"
    Public Const SC_CellID As String = "SC_CellID"

    Public Const N1_BCC As String = "N1_BCC"
    Public Const N1_BCCH As String = "N1_BCCH"
    Public Const N1_NCC As String = "N1_NCC"
    Public Const N1_RxLev As String = "N1_RxLev"
    Public Const N2_BCC As String = "N2_BCC"
    Public Const N2_BCCH As String = "N2_BCCH"
    Public Const N2_NCC As String = "N2_NCC"
    Public Const N2_RxLev As String = "N2_RxLev"
    Public Const N3_BCC As String = "N3_BCC"
    Public Const N3_BCCH As String = "N3_BCCH"
    Public Const N3_NCC As String = "N3_NCC"
    Public Const N3_RxLev As String = "N3_RxLev"
    Public Const N4_BCC As String = "N4_BCC"
    Public Const N4_BCCH As String = "N4_BCCH"
    Public Const N4_NCC As String = "N4_NCC"
    Public Const N4_RxLev As String = "N4_RxLev"
    Public Const N5_RxLev As String = "N5_RxLev"
    Public Const N5_BCC As String = "N5_BCC"
    Public Const N5_BCCH As String = "N5_BCCH"
    Public Const N5_NCC As String = "N5_NCC"
    Public Const N6_BCC As String = "N6_BCC"
    Public Const N6_BCCH As String = "N6_BCCH"
    Public Const N6_NCC As String = "N6_NCC"
    Public Const N6_RxLev As String = "N6_RxLev"
End Class

Public Class IOSThematicKeys
    Public Const THEMATIC_ID As String = "ThematicID"
    Public Const OBJECT_NAME As String = "ObjectName"
    Public Const THEMATIC_TYPE As String = "ThematicType"
    Public Const TARGET_OBJECT As String = "TargetObject"
    Public Const DISTRIBUTION_METHOD As String = "DistributionMethod"
    Public Const ROUND_BY As String = "RoundBy"
    Public Const IS_GRANDUATED As String = "IsGraduated"
    Public Const IS_HALFPIE As String = "IsHalfPie"
    Public Const PIE_DIAMETER As String = "PieDiameter"


    Public Const THEMATIC_BINSID As String = "ThematicBinsID"
    Public Const REGION_COLOR As String = "RegionColor"
    Public Const REGION_TRANSPARENCY As String = "RegionTransparency"
    Public Const REGION_INTERIOR_TYPE As String = "RegioninteriorType"
    Public Const REGION_BORDER_LINEWIDTH As String = "RegionBorderLineWidth"
    Public Const SYMBOL_NUMBER As String = "SymbolNumber"
    Public Const SYMBOL_SIZE As String = "SymbolSize"
    Public Const RANGE_MIN As String = "RangeMin"
    Public Const RANGE_MAX As String = "RangeMax"
    Public Const REGION_BORDER_LINETRANSPARENCY As String = "RegionBorderLineTransparancy"
    Public Const SYMBOL_INTERIOR_COLOR As String = "SymbolInteriorColor"
    Public Const SYMBOL_BORDER_COLOR As String = "SymbolBorderColor"
    Public Const SYMBOL_INTERIOR_TRANSPARENCY As String = "SymbolInteriorTransparancy"
    Public Const SYMBOL_BORDERTRANSPARENCY As String = "SymbolBorderTransparancy"

    Public Const KPI_ID As String = "KPI_ID"
    Public Const KPI_TYPEID As String = "KPITypeID"
    Public Const KPI_TYPE As String = "KPIType"
End Class
